// Movie Data
export const moviesData = [
  {
    moodTags: ["adventure", "romance", "comedy"],
    isClassic: true,
    title: "The Princess Bride",
    poster:
      "https://m.media-amazon.com/images/I/91bTo-vbpXL._UF1000,1000_QL80_.jpg",
    year: 1987,
    genre: "Adventure/Romance/Comedy",
    rating: "PG",
  },
  {
    moodTags: ["horror", "thriller"],
    isClassic: false,
    title: "Get Out",
    poster:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSt77oFBZvVVK5dcW9fhw4Op1mGxz5-lMYosA&s",
    year: 2017,
    genre: "Horror/Thriller",
    rating: "R",
  },
  {
    moodTags: ["drama"],
    isClassic: true,
    title: "The Shawshank Redemption",
    poster:
      "https://images.jdmagicbox.com/comp/jd_social/news/2018jul21/image-119206-zkypi64x2m.jpg",
    year: 1994,
    genre: "Drama",
    rating: "R",
  },
  {
    moodTags: ["sci-fi", "adventure", "comedy"],
    isClassic: true,
    title: "Back to the Future",
    poster:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxI94rTPeDQWXkxS2ACv7cZ_lBXEeChl7AAw&s",
    year: 1985,
    genre: "Sci-Fi/Adventure/Comedy",
    rating: "PG",
  },
  {
    moodTags: ["action"],
    isClassic: false,
    title: "Mad Max: Fury Road",
    poster:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSm7Fj-Anokwc9XknU17VUYnYafD_a3aON1Lg&s",
    year: 2015,
    genre: "Action",
    rating: "R",
  },
  {
    moodTags: ["romantic musical", "drama"],
    isClassic: false,
    title: "La La Land",
    poster:
      "https://lionsgate.brightspotcdn.com/bf/d2/306cfd60415fa6f98f9f1280a3dd/lalaland-movies-he-poster-01.jpg",
    year: 2016,
    genre: "Romantic Musical/Drama",
    rating: "PG-13",
  },
  {
    moodTags: ["romance", "drama", "sci-fi"],
    isClassic: false,
    title: "Her",
    poster:
      "https://m.media-amazon.com/images/I/812qk45SqML._UF1000,1000_QL80_.jpg",
    year: 2013,
    genre: "Romance/Drama/Sci-Fi",
    rating: "R",
  },
  {
    moodTags: ["comedy", "fantasy", "romance"],
    isClassic: true,
    title: "Groundhog Day",
    poster:
      "https://m.media-amazon.com/images/I/81U49XBGlML._UF1000,1000_QL80_.jpg",
    year: 1993,
    genre: "Comedy/Fantasy/Romance",
    rating: "PG",
  },
  {
    moodTags: ["adventure"],
    isClassic: true,
    title: "Raiders of the Lost Ark",
    poster:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQr5qzRZ6Wc7I_KJBceg7xgLUqqMfIP4b4LvQ&s",
    year: 1981,
    genre: "Adventure",
    rating: "PG",
  },
  {
    moodTags: ["comedy"],
    isClassic: false,
    title: "The Grand Budapest Hotel",
    poster:
      "https://m.media-amazon.com/images/I/91HHTI-Yt4L._UF1000,1000_QL80_.jpg",
    year: 2014,
    genre: "Comedy",
    rating: "R",
  },
  {
    moodTags: ["thriller", "horror"],
    isClassic: true,
    title: "The Silence of the Lambs",
    poster:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTA0riD_c5HzEmIZg0ij29P-jhWjkYkEblcg&s",
    year: 1991,
    genre: "Thriller/Horror",
    rating: "R",
  },
  {
    moodTags: ["romance", "drama"],
    isClassic: true,
    title: "Casablanca",
    poster:
      "https://static.tvtropes.org/pmwiki/pub/images/casablanca_poster.JPG",
    year: 1942,
    genre: "Romance/Drama",
    rating: "PG",
  },
  {
    moodTags: ["animation"],
    isClassic: false,
    title: "Spider-Man: Into the Spider-Verse",
    poster:
      "https://www.sonypictures.com/sites/default/files/styles/max_560x840/public/title-key-art/spiderman_verse_rating_0.jpg?itok=N_U_lGHQ",
    year: 2018,
    genre: "Animation",
    rating: "PG",
  },
  {
    moodTags: ["sci-fi", "adventure"],
    isClassic: false,
    title: "Inception",
    poster: "https://upload.wikimedia.org/wikipedia/en/1/18/Inception_OST.jpg",
    year: 2010,
    genre: "Sci-Fi/Adventure",
    rating: "PG-13",
  },
  {
    moodTags: ["mystery", "thriller"],
    isClassic: false,
    title: "Knives Out",
    poster:
      "https://m.media-amazon.com/images/S/pv-target-images/715b26895bc51e28d9b1a6538b0dedc553a8655d15de6a4bd99ce4dbb56af87f._SX1080_FMjpg_.jpg",
    year: 2019,
    genre: "Mystery/Thriller",
    rating: "PG-13",
  },
  {
    moodTags: ["mystery", "thriller"],
    isClassic: true,
    title: "Primal Fear",
    poster:
      "https://m.media-amazon.com/images/I/51tqferJbWL._UF1000,1000_QL80_.jpg",
    year: 1996,
    genre: "Mystery/Thriller",
    rating: "PG-13",
  },

  {
    moodTags: ["romantic musical", "drama"],
    isClassic: true,
    title: "Notting Hill",
    poster:
      " https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p22928_p_v13_aq.jpg",
    year: 1996,
    genre: "Drama/Romantic musical",
    rating: "PG-13",
  },

  {
    moodTags: ["action"],
    isClassic: true,
    title: "Terminator 2",
    poster:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBuKTiR4UVMpj0XNBtdpA7jd41sUBJB6Z3yQ&s",
    year: 1991,
    genre: "Action",
    rating: "PG-13",
  },

  {
    moodTags: ["animation"],
    isClassic: true,
    title: "Toy Story",
    poster: " https://upload.wikimedia.org/wikipedia/en/1/13/Toy_Story.jpg",
    year: 1995,
    genre: "Animation",
    rating: "PG-13",
  },
  {
  moodTags: ["drama", "romance"],
  isClassic: false,
  title: "The Fault in Our Stars",
  poster: "https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/5C306EBB9CBDD39FC2D72BD79A063838810C4C9F1913AAEA3C9AF3E3FB01F279/scale?width=1200&aspectRatio=1.78&format=jpeg",
  year: 2014,
  genre: "Drama/Romance",
  rating: "PG-13",
},
{
  moodTags: ["sci-fi", "thriller", "drama"],
  isClassic: false,
  title: "Interstellar",
  poster: "https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
  year: 2014,
  genre: "Sci-Fi/Thriller/Drama",
  rating: "PG-13",
},
{
  moodTags: ["action", "sci-fi"],
  isClassic: false,
  title: "The Matrix",
  poster: "https://tse4.mm.bing.net/th/id/OIP.WytOcBJIlvfnmaVJjzSvEQHaFj?pid=Api&P=0&h=180",
  year: 1999,
  genre: "Action/Sci-Fi",
  rating: "R",
},
{
  moodTags: ["comedy", "romance"],
  isClassic: false,
  title: "Crazy Rich Asians",
  poster: "https://popcornusa.s3.amazonaws.com/movies/650/5984-12972-CrazyRic.jpg",
  year: 2018,
  genre: "Comedy/Romance",
  rating: "PG-13",
},
{
  moodTags: ["animation", "adventure"],
  isClassic: false,
  title: "Coco",
  poster: "https://images.alphacoders.com/109/thumb-1920-1095566.jpg",
  year: 2017,
  genre: "Animation/Adventure",
  rating: "PG",
},
{
  moodTags: ["drama"],
  isClassic: false,
  title: "The Pursuit of Happyness",
  poster: "https://static1.srcdn.com/wordpress/wp-content/uploads/2024/03/the-pursuit-of-happyness-movie-poster-showing-will-smith-and-jaden-smith-holding-hands-with-a-skyline-in-the-background.jpeg",
  year: 2006,
  genre: "Drama",
  rating: "PG-13",
},
{
  moodTags: ["horror", "thriller"],
  isClassic: false,
  title: "A Quiet Place",
  poster: "https://tse3.mm.bing.net/th/id/OIP.uBYeFirAoAqVZ5o_R0zuxAHaEK?pid=Api&P=0&h=180",
  year: 2018,
  genre: "Horror/Thriller",
  rating: "PG-13",
},
{
  moodTags: ["animation", "fantasy", "adventure"],
  isClassic: false,
  title: "How to Train Your Dragon",
  poster: "https://tse4.mm.bing.net/th/id/OIP.PsEoY6m70QE483tlephn1QHaJ4?pid=Api&P=0&h=180",
  year: 2010,
  genre: "Animation/Fantasy/Adventure",
  rating: "PG",
},
{
  moodTags: ["mystery", "thriller"],
  isClassic: false,
  title: "Shutter Island",
  poster: "https://tse1.mm.bing.net/th/id/OIP.3guYFkPvaljKp-1Idq_ppwHaEK?pid=Api&P=0&h=180",
  year: 2010,
  genre: "Mystery/Thriller",
  rating: "R",
},
{
  moodTags: ["romance", "drama"],
  isClassic: false,
  title: "The Notebook",
  poster: "https://tse1.mm.bing.net/th/id/OIP.jyHCbcfbVVDf-eZ2xKEDKQHaLH?pid=Api&P=0&h=180",
  year: 2004,
  genre: "Romance/Drama",
  rating: "PG-13",
},
{
  moodTags: ["sci-fi", "action"],
  isClassic: false,
  title: "Avatar",
  poster: "https://tse3.mm.bing.net/th/id/OIP.2VhxzF0tQHhH8CFuOQu3qgHaK-?pid=Api&P=0&h=180",
  year: 2009,
  genre: "Sci-Fi/Action",
  rating: "PG-13",
},
{
  moodTags: ["adventure", "fantasy"],
  isClassic: true,
  title: "The Lord of the Rings: The Fellowship of the Ring",
  poster: "https://tse2.mm.bing.net/th/id/OIP.RweRNv2Nfu_3MywYWaSrtQHaE8?pid=Api&P=0&h=180",
  year: 2001,
  genre: "Adventure/Fantasy",
  rating: "PG-13",
},
{
  moodTags: ["comedy", "drama"],
  isClassic: false,
  title: "The Intern",
  poster: "https://tse4.mm.bing.net/th/id/OIP.tMj3oBxNot0jtISPP8sJFAHaEK?pid=Api&P=0&h=180",
  year: 2015,
  genre: "Comedy/Drama",
  rating: "PG-13",
},
{
  moodTags: ["sci-fi", "thriller"],
  isClassic: false,
  title: "Ex Machina",
  poster: "https://tse3.mm.bing.net/th/id/OIP.8R6_zxnclZJLgAh2NsOkiQHaLH?pid=Api&P=0&h=180",
  year: 2014,
  genre: "Sci-Fi/Thriller",
  rating: "R",
},
{
  moodTags: ["romantic musical", "drama"],
  isClassic: true,
  title: "Titanic",
  poster: "https://tse1.mm.bing.net/th/id/OIP.k5pst8ReigO2ehTM9xbWsAHaJ4?pid=Api&P=0&h=180",
  year: 1997,
  genre: "Romantic Musical/Drama",
  rating: "PG-13",
},
{
  moodTags: ["animation", "comedy"],
  isClassic: false,
  title: "Inside Out",
  poster: "https://tse3.mm.bing.net/th/id/OIP.tPUaeCb8R6yl_yJtYn4p7gHaEN?pid=Api&P=0&h=180",
  year: 2015,
  genre: "Animation/Comedy",
  rating: "PG",
},
{
  moodTags: ["action", "thriller"],
  isClassic: false,
  title: "John Wick",
  poster: "https://static1.srcdn.com/wordpress/wp-content/uploads/2024/01/john-wick-franchise-poster.jpg",
  year: 2014,
  genre: "Action/Thriller",
  rating: "R",
},
{
  moodTags: ["adventure", "fantasy"],
  isClassic: true,
  title: "Harry Potter and the Sorcerer’s Stone",
  poster: "https://tse2.mm.bing.net/th/id/OIP.2NspUWLHGVl8_2I__9z1oQHaLH?pid=Api&P=0&h=180",
  year: 2001,
  genre: "Adventure/Fantasy",
  rating: "PG",
},
{
  moodTags: ["drama", "biography"],
  isClassic: false,
  title: "Oppenheimer",
  poster: "https://static1.srcdn.com/wordpress/wp-content/uploads/2023/05/oppenheimer-poster.jpg",
  year: 2023,
  genre: "Drama/Biography",
  rating: "R",
},
{
  moodTags: ["thriller", "mystery"],
  isClassic: false,
  title: "Gone Girl",
  poster: "https://m.media-amazon.com/images/I/91Q2dM5vQOL._AC_UF894,1000_QL80_.jpg",
  year: 2014,
  genre: "Thriller/Mystery",
  rating: "R",
},

];
